UsuariosCrud/Models/ErrorViewModel.cs
namespace UsuariosCrud.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

UsuariosCrud/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;


namespace Mvc.Controllers
{
  public class AuthController : Controller
  {
      public IActionResult Login()
      {
      return View();
      }

      public IActionResult Register()
      {
      return View();
      }
  }
  
}

UsuariosCrud/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;


namespace Mvc.Controllers
{
  public class DashboardController : Controller
  {
      public IActionResult Index()
      {
      return View();
      }
  }
  
}

UsuariosCrud/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;


namespace Mvc.Controllers
{
  public class ProductsController : Controller
  {
      public IActionResult Index()
      {
        return View();
      }

      public IActionResult Create()
      {
        return View();
      }

      public IActionResult Show()
      {
        return View();
      }

      public IActionResult Delete()
      {
        return View();
      }

      public IActionResult Update()
      {
        return View();
      }

      public IActionResult Edit()
      {
        return View();
      }
  }
  
}

UsuariosCrud/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;


namespace Mvc.Controllers
{
  public class UsuariosController : Controller
  {
      public IActionResult Index()
      {
      return View();
      }

      public IActionResult Create()
      {
      return View();
      }
      public IActionResult Show()
      {
      return View();
      }

      public IActionResult Delete()
      {
      return View();
      }

      public IActionResult Update()
      {
      return View();
      }

      public IActionResult Info()
      {
        return View();
      }

      public IActionResult Edit()
      {
      return View();
      }
  }
  
}

UsuariosCrud/Views/Dashboard/Index.cshtml
@{
  ViewBag.Title = "Dashboard";
}

<div class="main">

  <div class="contenedor">
      <h1>Bienvenidos a mi página web</h1>
  </div>

  <div class="buttons">
      <button><a asp-controller="Products" asp-action="Index">Gestión de productos</a></button>
      <button> <a asp-controller="" asp-action="Index">Regístrate</a></button>
      <button><a asp-controller="Usuarios" asp-action="Index">Gestión de usuarios</a></button>
  </div>
  
</div>

UsuariosCrud/Views/Products/Delete.cshtml
@{
    ViewBag.Title = "Producto Eliminado";
}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="main">
        <div class="links">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
            <a asp-controller="Usuarios" asp-action="Create">Crear nuevo usuario</a>
        </div>

        <section>
            <h1>Se ha eliminado con éxito el producto</h1>

            <div class="boton-volver">
                <button><a asp-controller="Usuarios" asp-action="Index">Ver listado de productos</a></button>
            </div>
        </section>
    </div>
</body>

</html>

UsuariosCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/usuarios.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/usuariosShow.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/usuarioCrear.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/usuarioDelete.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UsuariosCrud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">UsuariosCrud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Create">Regístrate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UsuariosCrud/Views/Usuarios/Create.cshtml
@{
    ViewBag.Title = "Crear usuario";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear usuario</title>
</head>

<body>

    <div class="main">
        <div class="links">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
            <a asp-controller="Usuarios" asp-action="Index">Gestión de usuarios</a>
        </div>

        <div class="container">
            <div class="title">
                <h1>Registro crear usuario</h1>
            </div>
            <div class="col-md-12">
                <div class="form-control">
                    <div class="mb-3">
                        <label for="text"><strong>Nombres</strong></label>
                        <input class="form-control" type="text">
                    </div>
                    <div class="mb-3">
                        <label for="text"><strong>Apellidos</strong></label>
                        <input class="form-control" type="text">
                    </div>
                    <div class="mb-3">
                        <label for="text"><strong>Correo</strong></label>
                        <input class="form-control" type="text">
                    </div>
                    <div class="mb-3">
                        <label for="text"><strong>Género</strong></label>
                        <input class="form-control" type="text">
                    </div>
                    <div class="mb-3">
                        <label for="text"><strong>Edad</strong></label>
                        <input class="form-control" type="text">
                    </div>

                    <button class="btnCrearUsuario btn" asp-controller="Usuarios" asp-action="Create">Crear nuevo
                        usuario</button>
                </div>
            </div>
        </div>

    </div>
</body>

</html>

UsuariosCrud/Views/Usuarios/Delete.cshtml
@{
    ViewBag.Title = "Usuario Eliminado";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="main">
        <div class="links">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
            <a asp-controller="Usuarios" asp-action="Create">Crear nuevo usuario</a>
        </div>

        <section>
            <h1>Se ha eliminado con éxito el usuario</h1>

            <div class="boton-volver">
                <button><a asp-controller="Usuarios" asp-action="Index">Ver listado de usuarios</a></button>
            </div>
        </section>
    </div>
</body>

</html>

UsuariosCrud/Views/Usuarios/Index.cshtml
@{
  ViewBag.Title = "Usuarios";
}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Listado de usuarios</title>
</head>

<body>
  <div class="main">

    <div class="links">
      <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
      <a asp-controller="Usuarios" asp-action="Index">Gestión de usuarios</a>
    </div>

    <div class="table">
      <div class="button">
        <a class="btnCrear btn" asp-controller="Usuarios" asp-action="Create">Crear nuevo usuario</a>
      </div>
      <table class="table text-center">
        <thead>
          <th>Nombres</th>
          <th>Apellidos</th>
          <th>Correo</th>
          <th>Género</th>
          <th>Edad</th>
          <th>Acciones</th>
        </thead>
        <tbody>
          <td>Robinson</td>
          <td>Cortés</td>
          <td>robinson@riwi.io</td>
          <td>M</td>
          <td>28</td>
          <td>
            <a class="btnEliminar btn " asp-controller="Usuarios" asp-action="Delete">Eliminar</a>
            <a class="btnEditar btn" asp-controller="Usuarios" asp-action="Update">Editar</a>
            <a class="btnDetalles btn" asp-controller="Usuarios" asp-action="Show">Detalles</a>
          </td>
        </tbody>
      </table>
    </div>


  </div>
</body>

</html>

UsuariosCrud/Views/Usuarios/Info.cshtml
@{
    ViewBag.Title = "Usuario Actualizado";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="main">
        <div class="links">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
            <a asp-controller="Usuarios" asp-action="Create">Crear nuevo usuario</a>
        </div>

        <section>
            <h1>Se ha actualizado con éxito el usuario</h1>

            <div class="boton-accion">
                <button><a asp-controller="Usuarios" asp-action="Index">Ver listado de usuarios</a></button>
            </div>
        </section>
    </div>
</body>

</html>

UsuariosCrud/Views/Usuarios/Show.cshtml
@{
    ViewBag.Title = "Detalles usuario";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles usuarios</title>
</head>

<body>
    <div class="main">

        <div class="links">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
            <a asp-controller="Usuarios" asp-action="Index">Gestión de usuarios</a>
        </div>

        <div class="title">
            <h1>Detalles del usuario</h1>
        </div>




        <table class="table mt-4">
            <thead>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Edad</th>
                <th>Correo</th>
                <th>Género</th>
            </thead>
            <tbody>
                <td>Test nombre</td>
                <td>Test Apellido</td>
                <td>Test edad</td>
                <td>correo@correo.com</td>
                <td>M</td>
            </tbody>
        </table>

        <div class="boton-volver">
            <button class=" btn btn-dark"><a asp-controller="Usuarios" asp-action="Index">Ver lista usuarios</a></button>
        </div>
    </div>
</body>

</html>

UsuariosCrud/Views/Usuarios/Update.cshtml
@{
    ViewBag.Title = "Actualizar usuario";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear usuario</title>
</head>

<body>

    <div class="main">
        <div class="links">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
            <a asp-controller="Usuarios" asp-action="Index">Gestión de usuarios</a>
        </div>

        <div class="container">
            <div class="title">
                <h1>Registro crear usuario</h1>
            </div>
            <div class="col-md-12">
                <div class="form-control">
                    <div class="mb-3">
                        <label for="text"><strong>Nombres</strong></label>
                        <input class="form-control" type="text" placeholder="Nombre">
                    </div>
                    <div class="mb-3">
                        <label for="text"><strong>Apellidos</strong></label>
                        <input class="form-control" type="text" placeholder="Apellidos">
                    </div>
                    <div class="mb-3">
                        <label for="text"><strong>Correo</strong></label>
                        <input class="form-control" type="text" placeholder="Correo">
                    </div>
                    <div class="mb-3">
                        <label for="text"><strong>Género</strong></label>
                        <input class="form-control" type="text" placeholder="Género">
                    </div>
                    <div class="mb-3">
                        <label for="text"><strong>Edad</strong></label>
                        <input class="form-control" type="text" placeholder="Edad">
                    </div>

                    <button class="btnCrearUsuario btn"><a asp-controller="Usuarios" asp-action="Info">Actualizar
                            Información</a></button>
                </div>
            </div>
        </div>

    </div>
</body>

</html>

UsuariosCrud/Views/Usuarios/UsuarioUpdate.cshtml
@{
    ViewBag.Title = "Usuario Actualizado";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="main">
        <div class="links">
            <a asp-controller="Dashboard" asp-action="Index">Inicio</a>
            <a asp-controller="Usuarios" asp-action="Create">Crear nuevo usuario</a>
        </div>

        <section>
            <h1>Se ha eliminado con éxito el usuario</h1>

            <div class="boton-volver">
                <button><a asp-controller="Usuarios" asp-action="Index">Ver listado de usuarios</a></button>
            </div>
        </section>
    </div>
</body>

</html>